name: Node.js CI

defaults:
  run:
    shell: bash
    working-directory: .

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
    - name: Install npm
      run: npm install -g npm@8
    - name: Install Dependencies
      run: npm ci
    - name: Build for Distribution
      run: npm run build
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release.zip'
        directory: 'build'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/release.zip"
